config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    get 'loans/revenue'
  end

  root to: 'welcome#index'

  resources :clients, only: %i[new create]
end

app/models/application_record.rb
# frozen_string_literal: true

# Base app model class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

# Client model
class Client < ApplicationRecord
  has_many :loans

  validates :name, presence: true

  accepts_nested_attributes_for :loans
end

app/models/loan.rb
# frozen_string_literal: true

# Loan model
class Loan < ApplicationRecord
  belongs_to :client
  has_many :payments

  validates :amount, presence: true,
                     numericality: { greater_than_or_equal_to: 0 }
  validates :term, presence: true,
                   numericality: { greater_than_or_equal_to: 0 }
  validates :rate, presence: true
  validates :payment_period, presence: true,
                             numericality: { greater_than_or_equal_to: 0 }
  validates :overdue_rate, presence: true
  validates :opening_date, presence: true

  accepts_nested_attributes_for :payments

  def paid
    payments.map(&:amount).reduce(:+)
  end

  # Returns how much interest was paid on the loan
  def interest_paid
    paid - amount
  end

  # Returns interest_paid to loan's amount ratio
  def actual_rate
    interest_paid / amount.to_f
  end

  def term_in_years
    term / 12.0
  end
end

app/models/payment.rb
# frozen_string_literal: true

# Payment model
class Payment < ApplicationRecord
  belongs_to :loan

  validates :date, presence: true
  validates :amount, presence: true,
                     numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ApplicationController
end

app/controllers/api/loans_controller.rb
# frozen_string_literal: true

# Represents API access to loans resource
class Api::LoansController < Api::ApplicationController
  before_action :validate_params

  def revenue
    loan = Loan.new(loan_params)
    @calc = LoanCalculator.new(loan)
  end

  private

  def loan_params
    params.permit(:amount, :term, :rate)
  end

  def validate_params
    required_params = %i[amount term rate]
    head(400) if required_params.any? { |key| params[key].blank? }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base app controller class
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

# Allows to create new clients
class ClientsController < ApplicationController
  def new
    @client = Client.new
    loans = @client.loans.build
    loans.payments.build
  end

  def create
    @client = Client.new(client_params)
    return redirect_to root_url if @client.save
    render action: :new
  end

  private

  def client_params
    params.require(:client).permit(
      :name,
      loans_attributes: [
        :amount, :term, :rate,
        :payment_period, :overdue_rate, :opening_date,
        payments_attributes: %i[date amount]
      ]
    )
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Main page controller
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Base app helpers module
module ApplicationHelper
end

app/views/clients/new.html.slim
div.col-12
  h3 New Client

  div.mt-4
    div.row
    = form_for @client, url: {action: 'create'} do |f|
      div.row
        div.col-sm-1
          = f.label :name
        div.col-sm-1
          = f.text_field :name, required: true
      div.row
        div.col-sm-12
          h5 Loans
          a#addLoan.btn.btn-success href='javascript:void(0)' Add
          div#loans.col-sm-12
            div#loanForm.col-sm-12.mt-3
              hr
              = render partial: 'clients/partials/loans_form', locals: { sup_form: f }
      div.row.mt-2
        div.col-sm-2
          = f.submit 'Create', class: 'btn btn-success'

app/views/clients/partials/_loans_form.html.slim
= sup_form.fields_for :loans do |loans_form|
  div.row
    div.col-sm-1
      = loans_form.label :amount
    div.col-sm-1
      = loans_form.number_field :amount, required: true, min: 0, step: 0.01
  div.row
    div.col-sm-1
      = loans_form.label :term
    div.col-sm-1
      = loans_form.number_field :term, required: true, min: 0
  div.row
    div.col-sm-1
      = loans_form.label :rate
    div.col-sm-1
      = loans_form.number_field :rate, required: true
  div.row
    div.col-sm-1
      = loans_form.label :payment_period
    div.col-sm-1
      = loans_form.number_field :payment_period, required: true, min: 0
  div.row
    div.col-sm-1
      = loans_form.label :overdue_rate
    div.col-sm-1
      = loans_form.number_field :overdue_rate, required: true
  div.row
    div.col-sm-1
      = loans_form.label :opening_date
    div.col-sm-1
      = loans_form.date_field :opening_date, required: true
  div.row
    div.col-sm-12
      h5 Payments
      a.addPayment.btn.btn-success href='javascript:void(0)' Add
      div.payments.col-sm-12
        div.paymentForm.col-sm-12.mt-2
          = render partial: 'clients/partials/payments_form', locals: { sup_form: loans_form }

app/views/clients/partials/_payments_form.html.slim
= sup_form.fields_for :payments do |payments_form|
  div.row
    div.col-sm-1
      = payments_form.label :date
    div.col-sm-1
      = payments_form.date_field :date, required: true
  div.row
    div.col-sm-1
      = payments_form.label :amount
    div.col-sm-1
      = payments_form.number_field :amount, required: true, min: 0, step: 0.01

app/views/layouts/application.html.slim
doctype html
html
  head
    title InvestCalc
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = yield

app/views/welcome/index.html.slim
div.col-12
  div.mt-2
    = link_to 'New Client', new_client_path, class: 'btn btn-secondary'

  h3.mt-5 Calculate your investment revenue

  div.mt-4
    form#revenueForm
      div.row
        div.col-sm-1
          = label_tag(:amount, 'Amount:')
        div.col-sm-1
          = number_field_tag(:amount, nil, required: true, min: 0, step: 0.01)
      div.row
        div.col-sm-1
          = label_tag(:term, 'Term:')
        div.col-sm-1
          = number_field_tag(:term, nil, required: true, min: 0)
      div.row
        div.col-sm-1
          = label_tag(:rate, 'Rate:')
        div.col-sm-1
          = number_field_tag(:rate, nil, required: true)
      div.row.mt-2
        div.col-sm-2
          input.btn.btn-success type='submit' value='Calculate'

  div.mt-5
    div.row
      div.col-sm-2
        p Expected Rate:
      div.col-sm-2
        p
          span#expectedRate
          span %
    div.row
      div.col-sm-2
        p Expected Revenue:
      div.col-sm-2
        p#expectedRevenue
    div.row
      div.col-sm-2
        p Actual Rate:
      div.col-sm-2
        p
          span#actualRate
          span %
    div.row
      div.col-sm-2
        p Actual Revenue:
      div.col-sm-2
        p#actualRevenue